---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 12.5.1

platforms:
- name: ubuntu-14.04
- name: ubuntu-12.04

suites:
- name: recursor
  run_list:
    - recipe[pdns::default]
  attributes:
- name: authoritative_pgsql_source
  run_list:
    - recipe[postgresql::server]
    - recipe[pdns::load_schema_pg]
    - recipe[pdns::default]
  attributes:
    pdns:
      build_method: source
      flavor: authoritative      
      authoritative:
        backends:
          - gpgsql
        config:
          launch: gpgsql
          gpgsql_dbname: 'powerdns'
          gpgsql_host: '127.0.0.1'
          gpgsql_user: 'pdns'
          gpgsql_password: 'test'        
    postgresql:
      password:
        postgres: wadus
- name: authoritative_pgsql_package
  run_list:
    - recipe[postgresql::server]
    - recipe[pdns::default]
  attributes:
    pdns:
      build_method: package
      flavor: authoritative
      authoritative:
        backends:
          - gpgsql
    postgresql:
      password:
        postgres: wadus
- name: slave_source
  run_list:
    - recipe[pdns::default]
  attributes: 
    pdns:
      build_method: source
      flavor: slave
- name: slave_package
  run_list:
    - recipe[pdns::default]
  attributes:
    pdns:
      build_method: package
      flavor: slave

