---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04

suites:
- name: default
  run_list:
    - recipe[pdns::default]
  attributes: {}
- name: authoritative
  run_list:
    - recipe[pdns::authoritative]
  attributes: {}
- name: backend_pgsql
  run_list:
    - recipe[pdns::backend_pgsql]
  attributes: {}
