---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-8.5
  - name: centos-6.8
  - name: centos-7.2

suites:
  - name: recursor
    run_list:
      - recipe[test::recursor_install_single]
    attributes:
  - name: recursor-multi
    run_list:
      - recipe[test::recursor_install_multi]
    attributes:
  - name: authoritative
    run_list:
      - recipe[test::authoritative_install_single]
    attributes:
