---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-8
  - name: centos-6
  - name: centos-7

suites:
  - name: recursor-multi
    run_list:
      - recipe[pdns_test::inspec_dependencies]
      - recipe[pdns_test::recursor_install_multi]
    attributes:
  - name: authoritative-multi
    run_list:
      - recipe[pdns_test::inspec_dependencies]
      - recipe[pdns_test::authoritative_install_multi]
    attributes:
  - name: authoritative-postgres
    includes: [
      'centos-7',
      'debian-8',
      'ubuntu-14.04',
      'ubuntu-16.04'
    ]
    run_list:
      - recipe[pdns_test::inspec_dependencies]
      - recipe[pdns_test::authoritative_install_single_postgres]
    attributes: