---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-15.10
  - name: ubuntu-14.04
  # - name: bento/centos-7.2

suites:
  - name: recursor
    run_list:
      - recipe[test::default]
    attributes:
