---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 11.16.4

platforms:
- name: ubuntu-14.04

suites:
- name: default
  run_list:
    - recipe[pdns::default]
  attributes: {}
- name: authoritative
  run_list:
    - recipe[pdns::authoritative]
  attributes: {}
- name: backend_pgsql
  run_list:
    - recipe[pdns::authoritative]
    - recipe[pdns::backend_pgsql]
    - recipe[pdns::authoritative_config]
  attributes: {}
